USE [master]
GO

/****** Object:  Database [borrowedbooks]    Script Date: 26.08.2024 11:06:42 ******/
CREATE DATABASE [borrowedbooks]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'borrowedbooks', FILENAME = N'D:\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\borrowedbooks.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'borrowedbooks_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\borrowedbooks_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [borrowedbooks].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [borrowedbooks] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [borrowedbooks] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [borrowedbooks] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [borrowedbooks] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [borrowedbooks] SET ARITHABORT OFF 
GO

ALTER DATABASE [borrowedbooks] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [borrowedbooks] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [borrowedbooks] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [borrowedbooks] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [borrowedbooks] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [borrowedbooks] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [borrowedbooks] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [borrowedbooks] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [borrowedbooks] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [borrowedbooks] SET  DISABLE_BROKER 
GO

ALTER DATABASE [borrowedbooks] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [borrowedbooks] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [borrowedbooks] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [borrowedbooks] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [borrowedbooks] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [borrowedbooks] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [borrowedbooks] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [borrowedbooks] SET RECOVERY FULL 
GO

ALTER DATABASE [borrowedbooks] SET  MULTI_USER 
GO

ALTER DATABASE [borrowedbooks] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [borrowedbooks] SET DB_CHAINING OFF 
GO

ALTER DATABASE [borrowedbooks] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [borrowedbooks] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [borrowedbooks] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [borrowedbooks] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [borrowedbooks] SET QUERY_STORE = ON
GO

ALTER DATABASE [borrowedbooks] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [borrowedbooks] SET  READ_WRITE 
GO

